### PR TITLE
Included method for creating `Json` from `BigDecimal`s

### PR DESCRIPTION
**Pull request by propensive**

### CODE REVIEW

**Comment by propensive** [comment]
I called the method `bigDecimal` rather than overloading `number`, which was about the only choice I had.

**Comment by travisbrown** [comment]
The `Json` API might change a bit more before the 0.1 release, but for now at least `bigDecimal` sounds right to me—I'd like to avoid overloading `number`. So thanks!—will merge when green.

**Comment by travisbrown** [comment]
I love how @codecov-io just makes up numbers sometimes…

**Comment by propensive** [comment]
Maybe they should give the percentage to 1 significant figure...

**Pull request merged**
